//_Main
export const SET_ERR_MSG = "SET_ERR_MSG";
export const CLEAR_ERR_MSG = "CLEAR_MSG_ERROR";
export const ADD_ALERT = "ADD_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";
export const SET_MAIN_LOADING = "SET_MAIN_LOADING";
export const SET_DEVICE = "SET_DEVICE";
export const SET_SPLASH = "SET_SPLASH";
export const SET_ALLOW_TO_CREATE = "SET_ALLOW_TO_CREATE";
export const FAST_ALERT = "FAST_ALERT";
export const HAS_END_PAGES = "HAS_END_PAGES";
export const SET_LAST_SCROLL = "SET_LAST_SCROLL";
export const SET_PREVENT_MODIFY = "SET_PREVENT_MODIFY";
export const HAS_TOUCH_SCREEN_DEVICE = "HAS_TOUCH_SCREEN_DEVICE";
export const CHANGE_GUEST_NAME = "CHANGE_GUEST_NAME";
export const SET_PROGRESS_MODE = "SET_PROGRESS_MODE";

// auth
export const SET_GUEST_TOKEN = "SET_GUEST_TOKEN";
export const GET_ERROR = "GET_ERROR";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const SIGN_IN = "SIGN_IN";
export const SEND_VERIFY_CODE = "SEND_VERIFY_CODE";
export const SET_REDIRECT_LOGIN = "SET_REDIRECT_LOGIN";
export const SET_AUTH_ALERT = "SET_AUTH_ALERT";
export const CLOSE_AUTH_ALERT = "CLOSE_AUTH_ALERT";
export const CLEAR_USER = "CLEAR_USER";
export const SET_FOLLOWERS = "SET_FOLLOWERS";
export const SET_FOLLOWINGS = "SET_FOLLOWINGS";
export const SET_FOLLOW_PAGE = "SET_FOLLOW_PAGE";
export const IS_LOGGED_OUT = "IS_LOGGED_OUT";
export const HAS_END_PAGE = "HAS_END_PAGE";
export const SET_PROFILE_PAGE = "SET_PROFILE_PAGE";

// calendar
export const SET_LOADING_CALENDAR = "SET_LOADING_CALENDAR";
export const GET_CALENDAR = "GET_CALENDAR";
export const SET_CALENDAR_EVENTS = "SET_CALENDAR_EVENTS";
export const GET_CALENDAR_EVENTS = "GET_CALENDAR_EVENTS";
export const MODIFY_CALENDAR_EVENTS = "MODIFY_CALENDAR_EVENTS";
export const SET_MONTH = "SET_MONTH";
export const CLEAR_MONTH = "CLEAR_MONTH";
export const SET_CALENDAR_TIME = "SET_CALENDAR_TIME";
export const CLEAR_CALENDAR_TIME = "CLEAR_CALENDAR_TIME";
export const SET_CALENDAR_DATE = "SET_CALENDAR_DATE";
export const CLEAR_CALENDAR_DATE = "CLEAR_CALENDAR_DATE";
export const EVENT_SELECTED = "EVENT_SELECTED";
export const CLEAR_LOADING_CALENDAR = "CLEAR_LOADING_CALENDAR";
export const CLEAR_CALENDAR_EVENTS = "CLEAR_CALENDAR_EVENTS";
export const SET_HOME_CALENDAR = "SET_HOME_CALENDAR";
export const SET_HAS_FIRST_TIME = "SET_HAS_FIRST_TIME";

// general
export const SET_ALERT = "SET_ALERT";
export const CLOSE_ALERT = "CLOSE_ALERT";
export const SET_LOADING = "SET_LOADING";
export const SHOW_SPLASH = "SHOW_SPLASH";

// media
export const GET_MEDIA_DATA = "GET_MEDIA_DATA";
export const SET_LOADING_MEDIA = "SET_LOADING_MEDIA";
export const GET_MORE_POSTS = "GET_MORE_POSTS";
export const GET_CATEGORY_POSTS = "GET_CATEGORY_POSTS";
export const SET_HOME_MEDIA = "SET_HOME_MEDIA";
export const CLEAR_LOADING_MEDIA = "CLEAR_LOADING_MEDIA";
export const SET_HAS_CATS = "SET_HAS_CATS";
export const SET_POST_PAGE = "SET_POST_PAGE";
export const SET_ALLOW_TO_CREATE_MEDIA = "SET_ALLOW_TO_CREATE_MEDIA";
export const SET_MEDIA_SEARCH = "SET_MEDIA_SEARCH";
export const SET_MEDIA_SEARCH_PAGE = "SET_MEDIA_SEARCH_PAGE";
export const HAS_END_MEDIA_SEARCH = "HAS_END_MEDIA_SEARCH";
export const SET_NEW_MEDIA_SEARCH = "SET_NEW_MEDIA_SEARCH";
export const SET_VIDEO_TIME = "SET_VIDEO_TIME";

// post
export const SET_LOADING_POST = "SET_LOADING_POST";
export const GET_SINGLE_POST = "GET_SINGLE_POST";
export const GET_COMMENTS = "GET_COMMENTS";
export const SEND_COMMENTS = "SEND_COMMENTS";
export const SEND_COMMENTS_REPORT = "SEND_COMMENTS_REPORT";
export const LIKE_COMMENT = "LIKE_COMMENT";
export const LIKE_POST = "LIKE_POST";
export const SET_MY_POSTS = "SET_MY_POSTS";
export const GET_LAST_POST_POSITION = "GET_LAST_POST_POSITION";

//products
export const SET_COMMENT_FORM = "SET_COMMENT_FORM";
export const SET_NEW_STORE_SEARCH = "SET_NEW_ADS_SEARCH";
export const SET_STORE_SEARCH = "SET_STORE_SEARCH";
export const SET_STORE_SEARCH_PAGE = "SET_STORE_SEARCH_PAGE";
export const HAS_END_SEARCH_STORE = "HAS_END_SEARCH_STORE";
export const SET_MY_PRODUCTS = "SET_MY_PRODUCTS";
export const SET_HAS_STORE = "SET_HAS_STORE";
export const SET_SINGLE_ORDER = "SET_SINGLE_ORDER";
export const SET_DISCOUNT = "SET_DISCOUNT";
export const SET_BASKET_DETAILS = "SET_BASKET_DETAILS";
export const SET_HOME_PRODUCT = "SET_HOME_PRODUCT";
export const SET_PRODUCT_LOADING = "SET_PRODUCT_LOADING";
export const CLEAR_PRODUCT_LOADING = "CLEAR_PRODUCT_LOADING";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_SINGLE_CAT = "SET_SINGLE_CAT";
export const SET_SINGLE_PRODUCT = "SET_SINGLE_PRODUCT";
export const CLEAR_SINGLE_PRODUCT = "CLEAR_SINGLE_PRODUCT";
export const SET_IN_FEATURE = "SET_IN_FEATURE";
export const CLEAR_IN_FEATURE = "CLEAR_IN_FEATURE";
export const SET_LIKE = "SET_LIKE";
export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const SET_BASKET_COUNT = "SET_BASKET_COUNT";
export const GET_BASKET = "GET_BASKET";
export const CHANGE_BASKET_COUNT = "CHANGE_BASKET_COUNT";
export const SET_TOTAL_PRICE = "SET_TOTAL_PRICE";
export const CLEAR_BASKET = "CLEAR_BASKET";
export const SET_COMMENTS = "SET_COMMENTS";
export const SET_LIKE_COMMENT = "SET_LIKE_COMMENT";
export const REPORT_COMMENT = "REPORT_COMMENT";
export const SUBMIT_COMMENT = "SUBMIT_COMMENT";
export const SET_ORDERS = "SET_ORDERS";
export const GET_LAST_PRODUCT_POSITION = "GET_LAST_PRODUCT_POSITION";
export const SET_ALLOW_TO_CREATE_PRODUCT = "SET_ALLOW_TO_CREATE_PRODUCT";

//ads
export const SET_SUBCATEGORY_ADS = "SET_SUBCATEGORY_ADS";
export const SET_ADS_SLIDER = "SET_ADS_SLIDER";
export const SET_HOME_ADS = "SET_HOME_ADS";
export const SET_ADS_LOADING = "SET_ADS_LOADING";
export const CLEAR_ADS_LOADING = "CLEAR_ADS_LOADING";
export const GET_ADS = "GET_ADS";
export const GET_CATS = "GET_CATS";
export const UPDATE_ADS = "UPDATE_ADS";
export const ADS_SINGLE = "ADS_SINGLE";
export const ADS_PAGE = "ADS_PAGE";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const SET_ADS_SEARCH = "SET_ADS_SEARCH";
export const SET_ADS_SEARCH_PAGE = "SET_ADS_SEARCH_PAGE";
export const HAS_END_SEARCH = "HAS_END_SEARCH";
export const SET_NEW_ADS_SEARCH = "SET_NEW_ADS_SEARCH";
export const SET_ADS_ORDER = "SET_ADS_ORDER";
export const GET_ADS_FIELDS = "GET_ADS_FIELDS";
export const HAS_END_FAVORITE_PAGE = "HAS_END_FAVORITE_PAGE";
export const SET_ADS_CATEGORY = "SET_ADS_CATEGORY";
export const SET_ALLOW_TO_CREATE_ADS = "SET_ALLOW_TO_CREATE_ADS";

//account
export const FOLLOW_ACCOUNT = "FOLLOW_ACCOUNT";
export const SET_MORE_WALLET = "SET_MORE_WALLET";
export const SET_WALLET = "SET_WALLET";
export const SET_FAVORITE = "SET_FAVORITE";
export const GET_LAST_PROFILE_POSITION = "GET_LAST_PROFILE_POSITION";
export const SET_LOADING_ACCOUNT = "SET_LOADING_ACCOUNT";
export const SET_ACCOUNT = "SET_ACCOUNT";
export const GET_ACCOUNT = "GET_ACCOUNT";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const ADD_PROFILE_IMAGE = "ADD_PROFILE_IMAGE";
export const GET_ACTIVE_SESSIONS = "GET_ACTIVE_SESSIONS";
export const SESSION_KILL = "SESSION_KILL";
export const SESSION_KILL_ALL = "SESSION_KILL_ALL";
export const SESSION_KILL_ALLOTHER = "SESSION_KILL_ALLOTHER";
export const SET_PROFILE = "SET_PROFILE";
export const ADD_LOCATION = "ADD_LOCATION";
export const ADD_LOCATIONS = "ADD_LOCATIONS";
export const SET_MORE_LOCATION = "SET_MORE_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const EDIT_LOCATION = "EDIT_LOCATION";
export const GET_HOME_ACCOUNTS = "GET_HOME_ACCOUNTS";
export const SET_PROFILE_TAB = "SET_PROFILE_TAB";

//cinema
export const SET_HOME_CINEMA = "SET_HOME_CINEMA";
export const SET_LOADING_CINEMA = "SET_LOADING_CINEMA";

//notifications
export const SET_NOTIFICATION_BAR = "SET_NOTIFICATION_BAR";
export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const SET_NOTIF_LOADING = "SET_NOTIF_LOADING";
export const SET_NOTIF_PAGE = "SET_NOTIF_PAGE";

//path
export const SET_PREV_PATH = "SET_PREV_PATH";

//fare
export const SET_FARE = "SET_FARE";
export const SET_HOME_FARE = "SET_HOME_FARE";
export const SET_FARES = "SET_FARES";
export const SET_FARE_LOADING = "SET_FARE_LOADING";
export const SET_FARE_SEARCH = "SET_FARE_SEARCH";
export const SET_FARE_SEARCH_PAGE = "SET_FARE_SEARCH_PAGE";
export const HAS_END_FARE_SEARCH = "HAS_END_FARE_SEARCH";
export const SET_NEW_FARE_SEARCH = "SET_NEW_FARE_SEARCH";
export const SET_ALLOW_TO_CREATE_FARE = "SET_ALLOW_TO_CREATE_FARE";
