name: AUTO-DEPLOY
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Packages
      run: npm install --force
      
    - name: Build page
      run: npm run build

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        commit-message: "Comitted by Max Base - GitHub Bot"
        branch: main
        title: "Auto deploy: Update build directory"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: cd ${{ secrets.SSH_ROOT_PATH }} && git pull
